#!/bin/sh


set -e

GROUP='stratio'
USER='sqoop'
DIR_INSTALL='/opt/sds/sqoop-server'
DIR_CONF='/etc/sds/sqoop-server'
DIR_LOG='/var/log/sds/sqoop-server'

# Add stratio group if it doesn't already exists
if ! getent group $GROUP >/dev/null 2>&1; then
groupadd ${GROUP}
fi

# Add stratio user if it doesn't already exists
if ! getent passwd $USER >/dev/null 2>&1; then
[ -d /opt ] || mkdir /opt
useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
else
usermod -G $GROUP $USER
fi


    chmod 755 /opt/sds/sqoop-server/bin/*
    chmod +x /etc/init.d/sqoop*

if [ ! -d "$DIR_LOG" ]; then
mkdir $DIR_LOG
fi

chown root:root /etc/init.d/sqoop-server

chown -R ${USER}:${GROUP} $DIR_INSTALL
chown -R ${USER}:${GROUP} $DIR_LOG
chown -R ${USER}:${GROUP} $DIR_CONF


chmod 755 /etc/init.d/sqoop-server
chmod 755 /opt/sds/sqoop-server/bin/server
chmod 644 /etc/default/sqoop*


/sbin/chkconfig --add sqoop-server

exit 0