#!/bin/sh

set -e


#DEB

GROUP='stratio'
USER='sqoop'
DIR_INSTALL='/opt/sds/sqoop-server'
DIR_CONF='/etc/sds/sqoop-server'
DIR_LOG='/var/log/sds/sqoop-server'


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP}
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi

  chown root:root /etc/init.d/sqoop-server

  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG

  chmod 755 /etc/init.d/sqoop-server
  chmod 755 /opt/sds/sqoop-server/bin/*
  chmod -R 775 $DIR_INSTALL
  chmod -R 775 $DIR_CONF
  chmod -R 775 $DIR_LOG

  chown -R ${USER}:${GROUP} /opt/sds/.m2

#  rm -rf /opt/sds/sqoop-server/config && ln -s $DIR_CONF /opt/sds/sqoop-server/config


  update-rc.d sqoop-server defaults
  ;;
esac
exit 0
