#!/bin/sh

set -e


#DEB

GROUP='stratio'
USER='sqoop'
DIR_INSTALL='/opt/sds/sqoop-server'
DIR_CONF='/etc/sds/sqoop-server'
DIR_LOG='/var/log/sds/sqoop-server'
DIR_RUN='/var/run/sds'

    chmod 755 /etc/init.d/sqoop-server
    chmod 755 /opt/sds/sqoop-server/bin
#    chmod 755 /opt/sds/sqoop-server.sh-server/bin/*
     chmod +x /opt/sds/sqoop-server/bin/server


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP}
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi


  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod -R 775 $DIR_INSTALL
  chmod -R 775 $DIR_LOG

  chown -R ${USER}:${GROUP} $DIR_RUN

#  sed -i 's!"$BASEDIR"/:/etc/sds/sqoop-server/config!/etc/sds/sqoop-server!g' /opt/sds/sqoop-server/bin/server

  update-rc.d sqoop-server defaults
  ;;
esac
exit 0