#!/bin/sh

set -e


#DEB

GROUP='stratio'
USER='sqoop'
DIR_INSTALL='/opt/sds/sqoop-server'
DIR_CONF='/etc/sds/sqoop-server'
DIR_LOG='/var/log/sds/sqoop-server'


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP}
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi

  chown root:root /etc/init.d/sqoop-server

  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG

  chown root:root /etc/default/sqoop-server-functions
  chown root:root /etc/default/sqoop-server-variables

  chmod 755 /etc/init.d/sqoop-server

  chown -R ${USER}:${GROUP} /opt/sds/.m2

  chmod 755 $DIR_CONF
  chmod 755 $DIR_LOG
  chmod 755 $DIR_INSTALL
  chmod 755 /opt/sds/sqoop-server/bin/*
  chmod 644 /etc/default/sqoop-server-functions
  chmod 644 /etc/default/sqoop-server-variables

    chown root:${GROUP} /etc/sds 2>/dev/null
    chmod 775 /etc/sds 2>/dev/null

    chown root:${GROUP} /var/log/sds 2>/dev/null
    chmod 775 /var/log/sds 2>/dev/null

    chown root:${GROUP} /var/run/sds 2>/dev/null
    chmod 775 /var/run/sds 2>/dev/null

    chown root:${GROUP} /opt/sds 2>/dev/null
    chmod 775 /opt/sds 2>/dev/null


  update-rc.d sqoop-server defaults
  ;;
esac
exit 0