#!/bin/sh

#RPM

set -e

GROUP='stratio'
USER='sqoop'


if [ "$1" = "2" ]; then
   service sqoop-server stop
fi

# Add stratio group if it doesn't already exists
if ! getent group $GROUP >/dev/null 2>&1; then
groupadd ${GROUP}
fi

if ! getent passwd $USER >/dev/null 2>&1; then
   useradd -M -d /opt/sds/sqoop-server -g $GROUP -s /bin/nologin $USER
fi

exit 0