#!/bin/bash

set -e
#DEB

GROUP='stratio'

case "$1" in
    configure)
        if ! getent group ${GROUP} >/dev/null 2>&1; then
            groupadd ${GROUP}
        fi
      if ! getent passwd $USER >/dev/null 2>&1; then
        [ -d /opt ] || mkdir /opt
        useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
      else
        usermod -G $GROUP $USER
      fi
esac

exit 0