#!/bin/sh
# Copyright (c) 2016 Stratio (http://stratio.com)
#

set -e

GROUP='stratio'
USER='sqoop'
DIR_INSTALL='/opt/sds/sqoop-shell'
DIR_CONF='/etc/sds/sqoop-shell'


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP}
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

    chown root:${GROUP} /etc/sds 2>/dev/null
    chmod 775 /etc/sds 2>/dev/null

    chown root:${GROUP} /var/log/sds 2>/dev/null
    chmod 775 /var/log/sds 2>/dev/null

    chown root:${GROUP} /var/run/sds 2>/dev/null
    chmod 775 /var/run/sds 2>/dev/null

    chown root:${GROUP} /opt/sds 2>/dev/null
    chmod 775 /opt/sds 2>/dev/null


  chown -R $USER:$GROUP $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chmod 755 $DIR_CONF
  chmod 755 $DIR_INSTALL
  chmod 755 $DIR_INSTALL/bin/*





  ;;
esac

