#!/bin/sh
# Copyright (c) 2016 Stratio (http://stratio.com)
#

set -e

GROUP='stratio'
USER='sqoop'
DIR_INSTALL='/opt/sds/sqoop-shell'
chmod 0755 /opt/sds/sqoop-shell/bin/*
chown -R $USER:$GROUP $DIR_INSTALL