#!/bin/sh
# Copyright (c) 2016 Stratio (http://stratio.com)
#

set -e

GROUP='stratio'
USER='sqoop'
DIR_INSTALL='/opt/sds/sqoop-shell'
DIR_CONF='/etc/sds/sqoop-shell'


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP}
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  chown -R root:$GROUP /opt/sds
  chown -R root:$GROUP /etc/sds
  chown -R $USER:$GROUP $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chmod 750 $DIR_CONF
  chmod 750 $DIR_INSTALL
  chmod 750 $DIR_INSTALL/bin/*





  ;;
esac
